//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MofinModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_Buscados
    {
        public int ID_Sistema { get; set; }
        public string Nombre { get; set; }
        public string Doc_ID { get; set; }
        public string Ente_Busca { get; set; }
        public Nullable<System.DateTime> Fec_Busqueda { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Pais_Busca { get; set; }
    }
}
