//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MofinModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_HistActClientes
    {
        public int ID_Sistema { get; set; }
        public string Codigo { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaCambio { get; set; }
    
        public virtual C_Clientes C_Clientes { get; set; }
    }
}
