//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MofinModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ProdServ
    {
        public int ID_Sistema { get; set; }
        public string Cod_Cliente { get; set; }
        public byte Tipo_ProdServ { get; set; }
        public byte Cod_Tipo { get; set; }
        public bool valor { get; set; }
    
        public virtual C_Clientes C_Clientes { get; set; }
    }
}
