//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MofinModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ValorItemConsExp
    {
        public int ID_Sistema { get; set; }
        public string empresa { get; set; }
        public Nullable<byte> CE_Opc1 { get; set; }
        public Nullable<byte> CE_Opc2 { get; set; }
        public Nullable<byte> CE_Opc3 { get; set; }
        public Nullable<byte> CE_Opc4 { get; set; }
        public Nullable<byte> CE_Opc5 { get; set; }
        public Nullable<byte> CE_Opc6 { get; set; }
        public Nullable<byte> CE_Opc7 { get; set; }
        public Nullable<byte> CE_Opc8 { get; set; }
        public Nullable<byte> CE_Opc9 { get; set; }
        public Nullable<byte> CE_Opc10 { get; set; }
        public Nullable<byte> CE_Opc11 { get; set; }
        public Nullable<byte> CE_Opc12 { get; set; }
        public Nullable<byte> CE_Opc13 { get; set; }
        public Nullable<byte> CE_Opc14 { get; set; }
        public Nullable<byte> CE_Opc15 { get; set; }
        public Nullable<byte> CE_Opc16 { get; set; }
        public Nullable<byte> CE_Opc17 { get; set; }
        public Nullable<byte> CE_Opc18 { get; set; }
        public Nullable<byte> CE_Opc19 { get; set; }
        public Nullable<byte> CE_Opc20 { get; set; }
        public Nullable<byte> CE_Opc21 { get; set; }
        public Nullable<byte> CE_Opc22 { get; set; }
        public Nullable<byte> CE_Opc23 { get; set; }
        public Nullable<byte> CE_Opc24 { get; set; }
        public Nullable<byte> CE_Opc25 { get; set; }
        public Nullable<byte> CE_Opc26 { get; set; }
        public Nullable<byte> CE_Opc27 { get; set; }
        public Nullable<byte> CE_Opc28 { get; set; }
        public Nullable<byte> CE_Opc29 { get; set; }
        public Nullable<byte> CE_Opc30 { get; set; }
    }
}
