//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MofinModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exp_Clientes
    {
        public string Tipo_Persona { get; set; }
        public string Status { get; set; }
        public string Codigo { get; set; }
        public string Doc_ID { get; set; }
        public Nullable<System.DateTime> Doc_ID_Fec_Venc { get; set; }
        public string Nombre { get; set; }
        public string Pais_Nacimiento { get; set; }
        public string Nacionalidad { get; set; }
        public string Pais_Residencia { get; set; }
        public string Estado { get; set; }
        public string Edad { get; set; }
        public string Tipo_PersJurid { get; set; }
        public string Tipo_Estruc { get; set; }
        public string PEP { get; set; }
        public string Vol_Operaciones { get; set; }
        public string Criptomonedas { get; set; }
        public string Profesión { get; set; }
        public string Activ_Comerc { get; set; }
        public string Email { get; set; }
        public string Uso_Cuenta { get; set; }
        public string Nivel_Riesgo { get; set; }
        public Nullable<decimal> Perfil_Financiero { get; set; }
        public Nullable<byte> Nro_Transac { get; set; }
        public string Ejecutivo { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> Fecha_Ult_Act { get; set; }
    }
}
