//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MofinModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Estados
    {
        public int ID_Sistema { get; set; }
        public short Codigo { get; set; }
        public int Cod_Compuesto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<byte> Valor { get; set; }
        public Nullable<bool> CondEspSeguridad { get; set; }
    
        public virtual M_Pais M_Pais { get; set; }
    }
}
