//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MofinModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Pais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_Pais()
        {
            this.M_Estados = new HashSet<M_Estados>();
        }
    
        public int ID_Sistema { get; set; }
        public short Codigo { get; set; }
        public string Cod_AlfaNum2 { get; set; }
        public string Cod_AlfaNum3 { get; set; }
        public string Descripcion { get; set; }
        public Nullable<byte> Valor { get; set; }
        public Nullable<bool> CondEspSeguridad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_Estados> M_Estados { get; set; }
    }
}
