//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MofinModeloEntorno
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Accesos
    {
        public int ID_Sistema { get; set; }
        public string ID_Usuario { get; set; }
        public string Cod_Empresa { get; set; }
        public string Cod_Grupo { get; set; }
    
        public virtual Empresas Empresas { get; set; }
    }
}
