//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MofinModeloEntorno
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        public int ID_Sistema { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Siglas { get; set; }
        public string Directorio { get; set; }
        public string Doc_ID { get; set; }
        public string Email { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Direccion { get; set; }
        public string Logo { get; set; }
        public string Cad_Conexion { get; set; }
        public string Proveedor { get; set; }
        public string Metadata { get; set; }
    }
}
