//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MofinModeloEntorno
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos
    {
        public int ID_Sistema { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Archivos { get; set; }
        public Nullable<bool> Opc_Sistema { get; set; }
        public Nullable<bool> Ops_Empresas { get; set; }
        public Nullable<bool> Ops_Grupos { get; set; }
        public Nullable<bool> Ops_Usuarios { get; set; }
        public Nullable<bool> Clientes { get; set; }
        public Nullable<bool> Cli_Monitor { get; set; }
        public Nullable<bool> Cli_Busqueda { get; set; }
        public Nullable<bool> Mon_Operaciones { get; set; }
        public Nullable<bool> Mon_Financiero { get; set; }
        public Nullable<bool> Mon_Operacional { get; set; }
        public Nullable<bool> Reportes { get; set; }
        public Nullable<bool> Tablas_Maestras { get; set; }
        public Nullable<bool> Tab_Maestras { get; set; }
    
        public virtual Grupo_Opciones Grupo_Opciones { get; set; }
    }
}
