//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MofinModeloEntorno
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opc_Sistema
    {
        public string FuenteLetra { get; set; }
        public Nullable<byte> Desktop_NroImgs { get; set; }
        public int ID_Sistema { get; set; }
        public Nullable<byte> IdiomaPredeterminado { get; set; }
        public Nullable<bool> PermitUserCamParam { get; set; }
        public Nullable<byte> PaisUso { get; set; }
        public Nullable<bool> BtnsNavegBarraHerram { get; set; }
        public Nullable<bool> PermitUserCambIdioma { get; set; }
        public Nullable<byte> FondoEscritorio { get; set; }
        public Nullable<byte> FormFecha { get; set; }
        public Nullable<byte> FormPuntodecimal { get; set; }
    }
}
