//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MofinModeloEntorno
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int ID_Sistema { get; set; }
        public string ID_Usuario { get; set; }
        public string Nombre { get; set; }
        public string Password { get; set; }
        public Nullable<byte> Cnfg_Desktop { get; set; }
        public Nullable<byte> Cnfg_Idioma { get; set; }
        public Nullable<byte> Cnfg_PaisUso { get; set; }
        public Nullable<byte> Cnfg_FormFecha { get; set; }
        public Nullable<bool> Cnfg_SonidoClick { get; set; }
        public Nullable<bool> Cnfg_BarraHerramientas { get; set; }
    }
}
